GAME TREE SCENARIOS
bosonprotocol/contracts pull request #103
Opened 2021-05-14 07:12 UTC by sriharikapu

Covers various scenarios of game tress
Implemented the following codes 

Actions included

- [x] buyer-commit
- [x] buyer-complain
- [x] buyer-redeem
- [x] buyer-refund
- [x] seller-cancel
- [x] seller-commit
- [x] seller-admitFault

Helpers included 

- [x] Delay
- [x] Formatter
- [x]  Check Balances

Also included

- [x] sign Transactions

Tests

- [x] Modularized

Scenarios Covered

-[x] SELLER LISTS A VOUCHER FOR SALE
-[x] BUYER PURCHASES A VOUCHER
-[x] BUYER REDEEMS A COMMITTED VOUCHER
-[x] BUYER CLAIMS REFUND FOR A COMMITTED VOUCHER
-[x] BUYER COMPLAINS ABOUT REDEEMED VOUCHER
-[x] BUYER COMPLAINS ABOUT REFUND VOUCHER
-[x] SELLER ACCEPTS REDEEM FAULT ON COMPLAIN
-[x] SELLER ACCEPTS REFUND FAULT ON COMPLAIN

2021-05-14 10:46 UTC, hswopeams requested changes
A couple of things

- It looks like the formatter didn't like something. That's what made the pipeline fail. Try running `./go tests:format_fix` and then recommitting
- Please move the actions folder and everything in it into a folder called testGameTree or similar. Right now it's not clear that the actions folder is for tests
- The tests output using console.log, but I don't see any assertions. It's assertions that make a test a test. For instance when balances are checked in "Check Balances" blocks, there should be an assertion instead of a `console.log`

2021-05-17 08:01 UTC, HristiyanG requested changes

2021-05-17 08:01 UTC, HristiyanG commented on testGameTree/5-buyer-commit-refund.js
> +    let refundedVoucher;
redundant variable

2021-05-17 08:03 UTC, HristiyanG commented
Just finished my review, left some comments there, but just still some general questions: 
- Why the old test were deleted? There were roughly about 400 test. Do these scenarios cover each and every missing test?
	- if that is not the case, please bring back the old test
	- please consider writing a script, responsible for the user interactions, and leave the `test` script for the unit testing
- Agreed with Heather that the `actions` folder needs to be moved into the tests, maybe renamed to testGameTreeActions or similar
- Agreed with Heather that the tests should be using assertions
- Do we need to test those actions over a testnet at all?
	- we can do it by running 2 different scripts then, 1 for testnet (e.g. Rinkeby), 1 locally
	- this way while run locally, we should not bother to fill in the config file. We can get the accounts from the local rpc, deploy a contract and fill in the required params automatically
- There should be something at the end indicating that the tests are completed. Currently when the process finishes I was misled that I am doing something wrong as there is not anything which prompts me how tests went
- Maybe a little more detailed README file would be good. I don't think the delay should be that long (30000) if we test the flow locally. Maybe even we could move it into the configs?
- `constant.js` exported from the `test` folder, and now moved to actions/helpers/constants. Do we need to do that. IMHO this should be in the test folder as it's own purpose is to serve the tests
- left some comments for removing the empty lines, commented lines and other

2021-05-17 19:04 UTC, sriharikapu commented on testGameTree/1-seller-create.js
> +
removed it

2021-05-19 04:38 UTC, sriharikapu commented on testGameTree/buyer/refundVoucher.js
> -// module.exports = RefundVoucherETHETH;
removed them

2021-05-19 04:38 UTC, sriharikapu commented on testGameTree/buyer/refundVoucher.js
> +                // console.log(output)
removed

2021-05-19 04:38 UTC, sriharikapu commented on testGameTree/helpers/checkBalance.js
> +
resolved

2021-05-19 04:38 UTC, sriharikapu commented on testGameTree/helpers/formatter.js
> +    // console.log(_input);
removed the commented line

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/helpers/formatter.js
> +
removed the commented lines

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/seller/cancelVoucherSet.js
>  // const seller = new ethers.Wallet(SELLER_SECRET, PROVIDER);
removed

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/seller/cancelVoucherSet.js
> -// let sellerRequestCancelorFault =
removed

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/seller/cancelVoucherSet.js
>                  // console.log(receipt)
removed

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/seller/cancelVoucherSet.js
> +                // console.log(output)
removed

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/seller/cancelVoucherSet.js
> -// module.exports = sellerRequestCancelorFault;
removed

2021-05-19 04:39 UTC, sriharikapu commented on testGameTree/seller/createVoucher.js
> +
removed

2021-05-19 04:40 UTC, sriharikapu commented on testGameTree/seller/createVoucher.js
> +// const seller = new ethers.Wallet(SELLER_SECRET, PROVIDER);
removed

2021-05-19 04:40 UTC, sriharikapu commented on testGameTree/seller/createVoucher.js
> +                // resolve(hash)
removed

2021-05-19 04:40 UTC, sriharikapu commented on testGameTree/seller/createVoucher.js
> +                // console.log(receipt.topics[2]);
removed

2021-05-19 04:40 UTC, sriharikapu commented on testGameTree/seller/createVoucher.js
> +                // console.log(output)
removed

2021-05-19 04:41 UTC, sriharikapu commented on testGameTree/seller/createVoucher.js
> +
removed

2021-05-19 04:43 UTC, sriharikapu commented on testGameTree/seller/faultVoucher.js
> +                    // console.log(err)
removed

2021-05-19 04:43 UTC, sriharikapu commented on testGameTree/seller/faultVoucher.js
> +                // resolve(hash)
removed

2021-05-19 04:44 UTC, sriharikapu commented on testGameTree/seller/faultVoucher.js
> +                // console.log(output)
removed

2021-05-19 04:44 UTC, sriharikapu commented on testGameTree/seller/faultVoucher.js
> +// })();
removed

2021-05-19 04:46 UTC, sriharikapu commented on testGameTree/seller/faultVoucher.js
>                  // console.log(receipt)
removed

2021-05-19 05:03 UTC, sriharikapu commented on testGameTree/2-seller-create-cancel.js
> +
removed

2021-05-19 05:03 UTC, sriharikapu commented on testGameTree/4-buyer-commit-redeem.js
> +
removed

2021-05-19 05:04 UTC, sriharikapu commented on testGameTree/6-buyer-commit-redeem-complain.js
> +
removed

2021-05-19 05:04 UTC, sriharikapu commented on testGameTree/7-buyer-commit-refund-complain.js
> +
removed

2021-05-19 05:05 UTC, sriharikapu commented on testGameTree/8-buyer-commit-redeem-complain-seller-fault.js
> +
removed

2021-05-19 05:05 UTC, sriharikapu commented on testGameTree/9-buyer-commit-refund-complain-seller-fault.js
> +
removed

2021-05-19 05:05 UTC, sriharikapu commented on testGameTree/9-buyer-commit-seller-fault.js
> +// const sellerCancel = require("./seller/cancelVoucherSet");
removed

2021-05-19 05:05 UTC, sriharikapu commented on testGameTree/9-buyer-commit-seller-fault.js
> +
removed

2021-05-19 05:06 UTC, sriharikapu commented on testGameTree/9-buyer-commit-seller-fault.js
> +
removed

2021-05-19 05:07 UTC, sriharikapu commented on testGameTree/buyer/commitVoucher.js
>                  // console.log(receipt);
removed

2021-05-19 05:09 UTC, sriharikapu commented on testGameTree/buyer/commitVoucher.js
>                      "correlationID":correlationID,
mofied

2021-05-19 05:10 UTC, sriharikapu commented on testGameTree/buyer/compainVoucher.js
> -// let ComplainVoucherETHETH =
removed

2021-05-19 05:10 UTC, sriharikapu commented on testGameTree/buyer/compainVoucher.js
>                  // console.log(receipt);
removed

2021-05-19 05:10 UTC, sriharikapu commented on testGameTree/buyer/compainVoucher.js
> +                // console.log(output)
removed

2021-05-19 05:11 UTC, sriharikapu commented on testGameTree/buyer/compainVoucher.js
> -// module.exports = ComplainVoucherETHETH;
removed

2021-05-19 05:11 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
> +// const BN = require('bn.js');
removed

2021-05-19 05:11 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
> +// const helpers = require('../helpers/constants')
removed

2021-05-19 05:11 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
removed

2021-05-19 05:11 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
> -// let RedeemVoucherETHETH =
removed

2021-05-19 05:11 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
>                  // console.log(receipt);
removed

2021-05-19 05:12 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
> +                // console.log(output)
removed

2021-05-19 05:12 UTC, sriharikapu commented on testGameTree/buyer/redeemVoucher.js
> -// module.exports = RedeemVoucherETHETH;
removed

2021-05-19 05:12 UTC, sriharikapu commented on testGameTree/buyer/refundVoucher.js
> +                // console.log(hash);
removed

2021-05-20 14:39 UTC, sriharikapu commented
Why the old test were deleted? There were roughly about 400 tests. Do these scenarios cover each and every missing test?
 - [x] Brought Back the previous test
 
 Agreed with Heather that the actions folder needs to be moved into the tests, maybe renamed to testGameTreeActions or similar
 - [x] Renamed to testGameTree
 
 Agreed with Heather that the tests should be using assertions
 - [x] Added More assertions to tests
 
Do we need to test those actions over a testnet at all?
 - [x] You can set the provider to local or any testnet url so you can run them
 
There should be something at the end indicating that the tests are completed. Currently when the process finishes I was misled that I am doing something wrong as there is not anything which prompts me how tests went
- [x] once the tests finish you will be able to see the number of tests passing, 
 
Maybe a little more detailed README file would be good. I don't think the delay should be that long (30000) if we test the flow locally. Maybe even we could move it into the configs?
- [x] delay was set to 30000ms initially because of the delay in transactions getting confirmed lately, I had kept the delay to the config so you can customized for local test and testnet etc

constant.js exported from the test folder, and now moved to actions/helpers/constants. Do we need to do that. IMHO this should be in the test folder as it's own purpose is to serve the tests
- [x] Actually we don't need all the variables in the constants from the `constants.js`, I had removed the unused variables. also we can link to the previous constants

left some comments for removing the empty lines, commented lines and other
- [x] removed unnecessary empty lines mentioned

pipeline should succeed before merging
- [x]  made sure that pipeline passes

2021-06-04 21:05 UTC, hswopeams approved these changes

2021-06-05 20:05 UTC, sriharikapu commented
@hswopeams I think we can merge this once @HristiyanG approves it. Also I checked at my end everything works as expected.

2021-06-16 12:07 UTC, hswopeams commented
Changed gametree tests to run locally on Ganace instance started by the (Ruby) `go` script. Discussed with Holly, and it was decided that running locally is enough. There's no need to add complexity by adding config to also run against a testnet.

2021-09-03 09:03 UTC, thecryptofruit commented
@damir-bajramovic , please have a look if this is in your card, otherwise close. thanks

2021-11-02 21:56 UTC, mischat commented
All of the Game Tree has been incorporated into our unit test suite, we are happy that we are covering all of the game tree and more in `main` of this repo. This branch will be deleted.

2021-11-02 21:56 UTC, closed without merging