Consolidate calls remove explicit getters
bosonprotocol/contracts pull request #104
Opened 2021-05-14 13:31 UTC by hswopeams

This branch and related PR combine the Asana cards "consolidate calls to reduce external calls where possible" and "Make state variables public and remove explicit getter functions". A few of the changes will require changes to the front-end. 
The changes are as follows:

- Removed FundLimitsOracle.getETHLimit and getTokenLimit. Replace with ethLimit() and tokenLimit()
- Removed VoucherKernel. getVoucherStatus. Replaced with generated getter vouchersStatus(tokenIdVoucher)
- Removed VoucherKernel. getVoucherPaymentMethod. Replaced with generated getter paymentDetails(tokenSupplyId);
- Removed VoucherKernel.getOrderCosts. Replaced with generated getter promises(promiseKey)
- Removed VoucherKernel.getSupplyHolder. Replaced with generated getter promises(promiseKey)
- Removed VoucherKernel.getVoucherHolder. Replaced with direct call to IERC721(tokensContract).ownerOf(_tokenIdVoucher)
- Removed VoucherKernel.getVoucherPriceToken. Replaced with generated getter paymentDetails(tokenIdSupply)
- Removed VoucherKernel.getVoucherDepositToken. Replaced with generated getter paymentDetails(tokenIdSupply)
- Removed VoucherKernel.getSellerDeposit. Replaced with generated getter promises(promiseKey)
- Removed VoucherKernel.getBuyerOrderCosts. Replaced with generated getter promises(promiseKey)
- Removed VoucherKernel.getPromiseKey.  Function wasn't being used. Generated getter promises(index) can be used as an alternative.
- Removed VoucherKernel. getRemQtyForSupply. Replaced with direct call to IERC1155721.balanceOf() because that’s all this function does
- Removed Cashier getEscrowAmount and getEscrowTokensAmount. Replace with calls to generated getters escrow(address) and escrowTokens(address, address)

2021-05-17 11:30 UTC, HristiyanG requested changes

2021-05-17 11:31 UTC, HristiyanG commented
I am not sure if I follow the idea of the implementation of this PR. (Apologies in advance if that's the case). Eventually we could save a little bit from the VoucherKernel only at the deployment stage, but what i noticed is that we now have increased the external calls, rather than the opposite. Here are my thoughts: 
- why do we need to remove the `getETHLimit` && `getTokenLimit`  from the oracle contract? At the end they are only view functions which do not require any additional gas? At the end still we do not reduce the external calls.  Furthermore it will require changes at the front.
- IMHO it's easier to read, when we get values from `IVoucherKernel(voucherKernel).getOrderCosts(_tokenIdSupply)`  rather than from `IVoucherKernel(voucherKernel).promises(IVoucherKernel(voucherKernel).ordersPromise(_tokenIdSupply))` . Again we do not reduce external calls. Even we get more values that at the end are redundant? 
- VoucherKernel.paymentDetails - there are places that we just need the priceAddress, and others that we need tokenAddress. (e.g. Cashier.sol) I am not sure if we need every time to get directly from the mapping rather than their dedicated function? At some places being used this way become more ambiguous and harder to understand what `tokensAddress` stands for.  At the end I think we do not reduce external calls.
- Cashier.withdraw - external calls remain the same amount
- Cashier.withdrawDepositsSe -> previously we had 2 external calls for the initialisation of the `deposit` and `paymentMethod`, with the applied changed we increased them to 3? 
- Cashier.onERC721Transfer - for the initialisation of the function we had 3 external calls, with the applied changes are increased to 4
- Cashier.onERC1155Transfer - for the initialisation of the function we had 1 external call, with the applied changes are increased to 2
- VoucherKernel.cancelOrFault - we have 3 functions until we get the seller, previously 2
- VoucherKernel.cancelOrFaultVoucherSet - 3 fns to fetch the `remQty`, previously 2

2021-05-17 11:49 UTC, hswopeams commented on contracts/Cashier.sol
> -            tokenAddress = IVoucherKernel(voucherKernel).getVoucherPriceToken(
Do you mean I should change the` tokenAddress` variable name to something like `voucherPriceTokenAddress`

2021-05-17 11:54 UTC, hswopeams commented
> I am not sure I follow the idea of the implementation of this PR. (Apologies in advance if that's the case). Eventually we could save a little bit from the VoucherKernel only at the deployment stage, but what i noticed is that we now have increased the external calls, rather than the opposite. Here are my thoughts:
> 
> * why do we need to remove the `getETHLimit` && `getTokenLimit`  from the oracle contract? At the end they are only view functions which do not require any additional gas? At the end still we do not reduce the external calls.  Furthermore it will require changes at the front.
> * IMHO it's easier to read, when we get values from `IVoucherKernel(voucherKernel).getOrderCosts(_tokenIdSupply)`  rather than from `IVoucherKernel(voucherKernel).promises(IVoucherKernel(voucherKernel).ordersPromise(_tokenIdSupply))` . Again we do not reduce external calls. Even we get more values that at the end are redundant?
> * VoucherKernel.paymentDetails - there are places that we just need the priceAddress, and others that we need tokenAddress. (e.g. Cashier.sol) I am not sure if we need every time to get directly from the mapping rather than their dedicated function? At some places being used this way become more ambiguous and harder to understand what `tokensAddress` stands for and more error prone in future updates.  At the end I think we do not reduce external calls.
> * Cashier.withdraw - external calls remain the same amount
> * Cashier.withdrawDepositsSe -> previously we had 2 external calls for the initialisation of the `deposit` and `paymentMethod`, with the applied changed we increased them to 3?
> * Cashier.onERC721Transfer - for the initialisation of the function we had 3 external calls, with the applied changes are increased to 4
> * Cashier.onERC1155Transfer - for the initialisation of the function we had 1 external call, with the applied changes are increased to 2
> * VoucherKernel.cancelOrFault - we have 3 functions until we get the seller, previously 2
> * VoucherKernel.cancelOrFaultVoucherSet - 3 fns to fetch the `remQty`, previously 2

One of the big problems we have with the contracts is that they are too big. With the exception of ERC1155721, all of the state variables are public. There is no reason to have explicit getters in addition to the generated getters. This just increases the size of the contracts and doesn't add any functionality that isn't already provided.

2021-05-17 11:59 UTC, HristiyanG commented
> > I am not sure I follow the idea of the implementation of this PR. (Apologies in advance if that's the case). Eventually we could save a little bit from the VoucherKernel only at the deployment stage, but what i noticed is that we now have increased the external calls, rather than the opposite. Here are my thoughts:
> > 
> > * why do we need to remove the `getETHLimit` && `getTokenLimit`  from the oracle contract? At the end they are only view functions which do not require any additional gas? At the end still we do not reduce the external calls.  Furthermore it will require changes at the front.
> > * IMHO it's easier to read, when we get values from `IVoucherKernel(voucherKernel).getOrderCosts(_tokenIdSupply)`  rather than from `IVoucherKernel(voucherKernel).promises(IVoucherKernel(voucherKernel).ordersPromise(_tokenIdSupply))` . Again we do not reduce external calls. Even we get more values that at the end are redundant?
> > * VoucherKernel.paymentDetails - there are places that we just need the priceAddress, and others that we need tokenAddress. (e.g. Cashier.sol) I am not sure if we need every time to get directly from the mapping rather than their dedicated function? At some places being used this way become more ambiguous and harder to understand what `tokensAddress` stands for and more error prone in future updates.  At the end I think we do not reduce external calls.
> > * Cashier.withdraw - external calls remain the same amount
> > * Cashier.withdrawDepositsSe -> previously we had 2 external calls for the initialisation of the `deposit` and `paymentMethod`, with the applied changed we increased them to 3?
> > * Cashier.onERC721Transfer - for the initialisation of the function we had 3 external calls, with the applied changes are increased to 4
> > * Cashier.onERC1155Transfer - for the initialisation of the function we had 1 external call, with the applied changes are increased to 2
> > * VoucherKernel.cancelOrFault - we have 3 functions until we get the seller, previously 2
> > * VoucherKernel.cancelOrFaultVoucherSet - 3 fns to fetch the `remQty`, previously 2
> 
> One of the big problems we have with the contracts is that they are too big. With the exception of ERC1155721, all of the state variables are public. There is no reason to have explicit getters in addition to the generated getters. This just increases the size of the contracts and doesn't add any functionality that isn't already provided.

Does not the purpose of this PR is to reduce the external calls? But as stated they are now more than they were before. In my eyes are a little bit less readable and at some points more error prone with future updates. Let's see what @thecryptofruit and @thcrnk think on that matter?

2021-05-17 12:05 UTC, hswopeams commented
> > > I am not sure I follow the idea of the implementation of this PR. (Apologies in advance if that's the case). Eventually we could save a little bit from the VoucherKernel only at the deployment stage, but what i noticed is that we now have increased the external calls, rather than the opposite. Here are my thoughts:
> > > 
> > > * why do we need to remove the `getETHLimit` && `getTokenLimit`  from the oracle contract? At the end they are only view functions which do not require any additional gas? At the end still we do not reduce the external calls.  Furthermore it will require changes at the front.
> > > * IMHO it's easier to read, when we get values from `IVoucherKernel(voucherKernel).getOrderCosts(_tokenIdSupply)`  rather than from `IVoucherKernel(voucherKernel).promises(IVoucherKernel(voucherKernel).ordersPromise(_tokenIdSupply))` . Again we do not reduce external calls. Even we get more values that at the end are redundant?
> > > * VoucherKernel.paymentDetails - there are places that we just need the priceAddress, and others that we need tokenAddress. (e.g. Cashier.sol) I am not sure if we need every time to get directly from the mapping rather than their dedicated function? At some places being used this way become more ambiguous and harder to understand what `tokensAddress` stands for and more error prone in future updates.  At the end I think we do not reduce external calls.
> > > * Cashier.withdraw - external calls remain the same amount
> > > * Cashier.withdrawDepositsSe -> previously we had 2 external calls for the initialisation of the `deposit` and `paymentMethod`, with the applied changed we increased them to 3?
> > > * Cashier.onERC721Transfer - for the initialisation of the function we had 3 external calls, with the applied changes are increased to 4
> > > * Cashier.onERC1155Transfer - for the initialisation of the function we had 1 external call, with the applied changes are increased to 2
> > > * VoucherKernel.cancelOrFault - we have 3 functions until we get the seller, previously 2
> > > * VoucherKernel.cancelOrFaultVoucherSet - 3 fns to fetch the `remQty`, previously 2
> > 
> > 
> > One of the big problems we have with the contracts is that they are too big. With the exception of ERC1155721, all of the state variables are public. There is no reason to have explicit getters in addition to the generated getters. This just increases the size of the contracts and doesn't add any functionality that isn't already provided.
> 
> Does not the purpose of this PR is to reduce the external calls? But as stated they are now more than they were before. In my eyes are a little bit less readable and at some points more error prone on future updates. Let's see what @thecryptofruit and @thcrnk think on that matter?

As I stated  in the description above, this combines two cards. Furthermore, I don't agree that the number of calls has increased. There were several cases where there were calls being made to another contract to functions that read from two different mappings -- two SLOADS. One of these SLOADS common to these functions was reading the promiseKey from the `ordersPromise` mapping before reading from the `promises` mapping. Two or three of these functions would be called from the same calling contract, which means the same promisKey was SLOADed from `ordersPromise` mapping 2 - 3 times when it only needs to be read once.

2021-05-18 07:15 UTC, HristiyanG commented
Looks like we are on a different opinion, which is good, cause this way we could bring the contracts to the next level. The truth is born in the dispute. I decided to go "by the numbers" so to see how all these things reflect to the gas being used in the corresponding transactions. Here is what my research tells

- Cashier.withdraw - gas cost increased from what we have on the main branch from 3 to 10k depending on the lifecycle of a voucher 
- Cashier.withdrawDepositsSe
	- ETH ETH: main 73069 / PR#104 95862
	- TKN TKN: main 105873 / PR#104 130595
	- ETH TKN: main  105839 / PR#104 130561
	- TKN ETH: main  73103 / PR#104 95896
- Cashier.onERC721Transfer -  main: 106020 / PR#104: 116044
- Cashier.onERC1155Transfer - main: 100555 / PR#104:  111987
- VoucherKernel.cancelOrFault - main: 49540 / PR#104: 60705
- VoucherKernel.cancelOrFaultVoucherSet
	- ETH ETH: main 73069/ PR#104 95862
	- TKN TKN: main 105873 / PR#104 130595
	- ETH TKN: main 105839 / PR#104 130561
	- TKN ETH: main 73103 / PR#104 95896

2021-05-31 14:28 UTC, hswopeams commented
We decided to go in a different direction -- make start variables private so there are no duplicate generated getters. Keeping the explicit getters. Closing this pull request.

2021-05-31 14:28 UTC, closed without merging