Feature/gha
bosonprotocol/contracts pull request #123
Opened 2021-08-19 06:14 UTC by moh-abk

2021-10-19 21:25 UTC, mischat requested changes
I wonder why we choice to upgrade hardhat and as a result a bunch of dependencies, did we need to make those changes to enable the GH actions ?

Furthermore, i think the actions are missing some environment variables. I will pulled in the commits from the main branch and it seems to have failed since.

2021-10-22 14:21 UTC, mischat submitted a review, later dismissed

2021-10-27 08:10 UTC, dohaki submitted a review, later dismissed
LGTM

2021-10-27 12:34 UTC, dohaki approved these changes
LGTM 👍

2021-10-27 12:58 UTC, mischat approved these changes

2021-10-27 12:58 UTC, merged