Unit tests - 2_test_fullpath_with_permit
bosonprotocol/contracts pull request #165
Opened 2021-10-11 07:10 UTC by zajck

Unit test `2_test_fullpath_with_permit is updated`, to more prcisely check emited events and state changes.

Utils functions were changes, so I had to update some other test (`3_withdrawals`, `4_pausing_contracts`, `6_erc1155721`, `11_gate` and `12_conditional_commit`) files too in order to build to success. Otherwise these files were not changed.

Some other comments:
- did not add tests for `commit`, `redeem`, `refund` and `COF` for every combination, since these methods are properly tested in `1_test_fullpath` and are not payment type specific
- some block of the code could be rewritten so the style would be more consistent, but at the moment it would just take time without any other positive effect

2021-10-11 11:49 UTC, bidyut-arianelabs requested changes

2021-10-12 07:50 UTC, hswopeams requested changes

2021-10-12 07:50 UTC, hswopeams commented
It looks good overall. Much improved. There are still a few things we need to address.

2021-10-13 11:30 UTC, zajck reviewed
All inline code comments are resolved.

Not resolved yet:
`IERC721Receiver(_to).onERC721Received.selector` and `IERC1155Receiver(_to).onERC1155Received.selector`

2021-10-13 11:50 UTC, bidyut-arianelabs requested changes

2021-10-13 12:52 UTC, bidyut-arianelabs approved these changes
Looks good to me 👍

2021-10-13 13:00 UTC, hswopeams approved these changes

2021-10-13 13:01 UTC, merged