Unit tests 3 withdraw scenarios
bosonprotocol/contracts pull request #197
Opened 2021-10-15 13:53 UTC by zajck

Updated section `'Withdraw scenarios'`

Other two sections were not updated (or removed). If/when they are moved to separate file, they should be removed from here.

2021-10-18 08:57 UTC, bidyut-arianelabs requested changes

2021-10-18 14:54 UTC, bidyut-arianelabs submitted a review, later dismissed
Looks good to me 👍

2021-10-19 10:47 UTC, hswopeams requested changes
Please add the scenarios we discussed.

2021-10-19 16:09 UTC, hswopeams submitted a review, later dismissed

2021-10-21 08:44 UTC, hswopeams approved these changes

2021-10-21 08:54 UTC, bidyut-arianelabs approved these changes
Looks good to me 👍

2021-10-21 09:12 UTC, merged