Address slither reentrancy findings
bosonprotocol/contracts pull request #204
Opened 2021-10-18 22:14 UTC by cliffhall

* In slither.db.json
  - updated via slither's triage-mode, but something's bonkers about slither and sometimes things stay ignored, sometimes they don't. Also just running it in normal mode several times will give different results. Therefore, I have no confidence that we'll ever get it to totally shut up, and we should just consider it helpful guide, and not like code coverage output which can eventually reach 100%

* In BosonRouter.sol,
  - removed a lot of whitespace
  - added virtual keyword to requestCreateOrderETHETH method, so it can be overriden by MockBosonRouter.sol
  - added nonReentrant modifier to methods:
    - requestCreateOrderTKNTKNWithPermit
    - requestCreateOrderTKNTKNWithPermitConditional
    - requestCreateOrderETHTKNWithPermit
    - requestCreateOrderETHTKNWithPermitConditional
    - requestCreateOrderTKNETH
    - requestCreateOrderTKNETHConditional
  - removed nonReentrant modifier from requestCreateOrderTKNETHInternal method, which is internal and the modifier has already been invoked on all callers.

* In Cashier.sol,
  - added nonReentrant modifier to methods:
    - onERC721Transfer
    - onERC1155Transfer

* In DAITokenWrapper.sol,
  - imported and extended ReentrancyGuard
  - added nonReentrant modifier to methods:
    - permit

* In ERC1155ERC721.sol,
  - imported and extended ReentrancyGuard
  - added nonReentrant modifier to methods:
    - safeTransferFrom
    - _transferFrom

* In MockBosonRouter.sol,
  - removed all imports except BosonRouter
  - extended BosonRouter
  - added constructor that passes its args to BosonRouter
  - removed all functions except
    - requestCreateOrderETHETH (which sends an invalid payment type to requestCreateOrder for a specific test)
    - transferFromAndAddEscrowTest

* In VoucherKernel.sol,
  - imported and extended ReentrancyGuard
  - added nonReentrant modifier to methods:
    - fillOrder
    - cancelOrFaultVoucherSet

This fixes #177

2021-10-19 14:10 UTC, hswopeams requested changes
Looks good for the most part. I have one request for change and a few questions. See inline.

2021-10-19 16:32 UTC, hswopeams submitted a review, later dismissed
Approving assuming the build issue will get fixed.

2021-10-19 19:25 UTC, hswopeams approved these changes

2021-10-20 14:45 UTC, bidyut-arianelabs approved these changes
Looks good to me 👍

2021-10-20 15:02 UTC, merged