Unit tests for 3_withdrawals.ts: Withdraw on disaster
bosonprotocol/contracts pull request #205
Opened 2021-10-19 11:08 UTC by bidyut-arianelabs

In this PR, I am adding the remaining unit test cases for the `Withdraw on Disaster` scenarios.

Depends on https://github.com/bosonprotocol/contracts/pull/197

2021-10-19 12:56 UTC, hswopeams requested changes
It looks pretty good. I have a a few small requests for change. In addition, I have a functonal question. According to the `setDisasterState` comments, "Once this functions is triggered, contracts cannot be unpaused anymore".

I don't see a test case for this. There's also no indication that the functionality was built. I think the question is if it should be added or not. I think it's a functional question we shoud discuss in the team.

2021-10-19 14:16 UTC, zajck requested changes

2021-10-21 10:26 UTC, zajck submitted a review, later dismissed

2021-10-21 13:18 UTC, zajck approved these changes

2021-10-21 13:26 UTC, hswopeams approved these changes

2021-10-21 13:28 UTC, merged