Remediate BRR-03C
bosonprotocol/contracts pull request #210
Opened 2021-10-20 19:05 UTC by cliffhall

* In BosonRouter.sol,
  - requestCreateOrder and checkLimits methods
    - Verified that all callers are passing calldata that would otherwise be copied needlessly to memory
    - _metadata argument
       - Changed location from memory to calldata
       - Verified compilation and unit tests all succeed.
* This fixes #180

2021-10-21 06:58 UTC, zajck requested changes
Funcion `checkLimits` should be updated too.

2021-10-21 09:24 UTC, hswopeams reviewed
I agree with @zajck that `checkLimits` needs to be changed too.

2021-10-21 16:42 UTC, hswopeams approved these changes

2021-10-22 03:49 UTC, zajck approved these changes

2021-10-22 07:08 UTC, merged