Inexistent error messages
bosonprotocol/contracts pull request #219
Opened 2021-10-21 14:43 UTC by bidyut-arianelabs

This PR resolves https://github.com/bosonprotocol/contracts/issues/186

2021-10-21 14:57 UTC, cliffhall submitted a review, later dismissed
LGTM! 👍

2021-10-21 16:28 UTC, hswopeams requested changes

2021-10-22 11:06 UTC, zajck submitted a review, later dismissed

2021-10-22 11:29 UTC, mischat approved these changes
This looks good to me.

2021-10-22 11:39 UTC, hswopeams approved these changes

2021-10-22 11:39 UTC, merged