[Draft] Don't run GHA on draft PRs
bosonprotocol/contracts pull request #273
Opened 2021-11-08 11:45 UTC by bidyut-arianelabs

This PR skips Build/Test/Synk when PR is in `Draft` status.

2021-11-08 18:36 UTC, cliffhall approved these changes, later dismissed
LGTM! 👍

2021-11-10 12:50 UTC, hswopeams approved these changes, later dismissed

2021-11-10 13:12 UTC, hswopeams requested changes
It looks like ci.yaml is now missing
 - name: Upload Gas reporter output
        uses: actions/upload-artifact@v2
        with:
          name: gas-reporter-report
          path: GasReport.txt
Update: this is in cluded in PR 275, which hasn't been merged yet.

2021-11-10 13:15 UTC, hswopeams approved these changes

2021-11-10 20:59 UTC, cliffhall approved these changes
LGTM! 👍

2021-11-10 21:00 UTC, merged