Fix/update readme
bosonprotocol/contracts pull request #280
Opened 2021-11-16 16:59 UTC by Rhian

This is an update to the README to reflect the fact that we have now deployed the contracts to the live network.

2021-11-16 17:42 UTC, hswopeams approved these changes, later dismissed

2021-11-16 18:16 UTC, cliffhall requested changes

2021-11-16 18:16 UTC, cliffhall commented on README.md
> +This is version 1 of the Protocol. You will find the addresses of the deployed contracts on Ethereum's main net and Rinkeby test net [here](https://github.com/bosonprotocol/contracts/blob/main/docs/c
Change Rinkeby to Ropsten

2021-11-16 18:23 UTC, Rhian commented on README.md
> +This is version 1 of the Protocol. You will find the addresses of the deployed contracts on Ethereum's main net and Rinkeby test net [here](https://github.com/bosonprotocol/contracts/blob/main/docs/c
Updated, thanks!

2021-11-16 18:37 UTC, cliffhall approved these changes
LGTM! 👍

2021-11-17 08:39 UTC, hswopeams approved these changes

2021-11-17 08:39 UTC, merged