Remediate DAI-01S
bosonprotocol/contracts pull request #287
Opened 2021-12-02 13:32 UTC by bidyut-arianelabs

fixes https://github.com/bosonprotocol/contracts/issues/285

2021-12-02 13:57 UTC, zajck submitted a review, later dismissed

2021-12-02 17:13 UTC, hswopeams requested changes

2021-12-02 17:13 UTC, hswopeams commented on contracts/DAITokenWrapper.sol
>      }
Please change to` _daiTokenAddress` in the emitted log so as to avoid an unnecessary SLOAD

2021-12-03 09:06 UTC, hswopeams approved these changes

2021-12-03 09:09 UTC, zajck approved these changes

2021-12-03 09:10 UTC, merged