Refactor withdraw
bosonprotocol/contracts pull request #309
Opened 2022-02-10 12:15 UTC by zajck

Major changes:

introduced new internal function reduceEscrowAmountDeposits to reduce code duplication
introduced distributeAndWithdraw which does similar to what withdraw did before, except it does it only for specified entity
added external function withdrawSingle which allows withdrawing for specific entity
withdraw still exists and it's behaviour is exactly the same as before the changes. The biggest difference is that if this fails, there always exist

Old test are passing (with just minor modifications).
I added new test file `3_1_withdrawals_per_entity` which performs similar actions as the existing `3_withdrawals` except separate calls are made for each entity.
It extends the running time for around 20%.

2022-02-10 14:22 UTC, bidyut-arianelabs requested changes

2022-02-10 18:00 UTC, hswopeams submitted a review, later dismissed

2022-02-11 09:08 UTC, hswopeams submitted a review, later dismissed

2022-02-11 09:09 UTC, zajck commented on contracts/VoucherKernel.sol
> +        // }
Removed

2022-02-11 09:09 UTC, zajck commented on contracts/VoucherKernel.sol
> +        // }
Removed

2022-02-11 09:09 UTC, zajck commented on contracts/VoucherKernel.sol
> +        return promises[promiseKey].depositSe +  promises[promiseKey].depositBu;
Fixed

2022-02-11 09:10 UTC, bidyut-arianelabs submitted a review, later dismissed
Looks good to me 👍

2022-02-14 08:21 UTC, bidyut-arianelabs approved these changes

2022-02-14 08:36 UTC, hswopeams approved these changes

2022-02-14 08:41 UTC, merged