Check whether PR author name is dependabot
bosonprotocol/contracts pull request #321
Opened 2022-02-24 16:30 UTC by bidyut-arianelabs

Github treats `app/dependabot` as the author name of the PRs as shown in attached image below.
In this PR, I am running deploy script to PRs whose author is dependabot.

## Github PR author name:
<img width="2542" alt="Screenshot 2022-02-24_21-54-44-465" src="https://user-images.githubusercontent.com/91169722/155565309-eeab3f3a-3395-4430-aa7e-6ccdb1b64b50.png">

2022-02-24 17:30 UTC, cliffhall approved these changes, later dismissed
LGTM!

2022-02-24 17:36 UTC, hswopeams requested changes
This didn't solve the problem. We need to close this PR though. We don't have time to fix this now, and it's not a big problem.

2022-03-09 13:23 UTC, hswopeams approved these changes

2022-03-09 13:48 UTC, zajck approved these changes

2022-03-09 13:48 UTC, merged