Verify that deployed address matches calculated address
bosonprotocol/contracts pull request #351
Opened 2022-03-14 16:45 UTC by zajck

In `deploy` we calculate some address upfront and pass them into constructors of other contracts.
If there exist some pending transactions from the deployer at the the begining of the deployment, calculated addresses are wrong.

Previously we only checked at the end of the deployment if calculated addresses actually match the deployed addresses.

Now I changed it to check right after the deployment and terminate the process if mismatch is detected.

2022-03-14 17:15 UTC, hswopeams requested changes
I think this is a really good addition to the script. Please add it to` deploy-legacy.ts` as well

2022-03-14 17:26 UTC, zajck commented
> I think this is a really good addition to the script. Please add it to` deploy-legacy.ts` as well

Good point. Added.

2022-03-14 23:14 UTC, cliffhall approved these changes
LGTM! 👍

2022-03-15 13:43 UTC, hswopeams approved these changes

2022-03-15 13:43 UTC, merged