Fix norentrancy and minor refactoring
bosonprotocol/contracts pull request #94
Opened 2021-04-07 09:26 UTC by ali2251

2021-04-23 05:57 UTC, HristiyanG commented on contracts/VoucherKernel.sol
> -    bytes32[] public promiseKeys;
Why should we conceal the promiseKeys?

2021-04-23 06:00 UTC, HristiyanG commented
In general looking good. Just something to clarify - this PR states it fixes reentrancy, but there are a lot of linting changes. Can you make sure you run the pipeline locally before a PR, so we can all have similar linting?

2021-04-23 14:01 UTC, hswopeams requested changes
Make promiseKeys mapping public again.

2021-04-23 14:02 UTC, ali2251 commented on contracts/VoucherKernel.sol
> +    bytes32[] promiseKeys;
Sure, will add public back

2021-04-23 14:08 UTC, ali2251 commented
I am not sure why the linting changes occured and why they arent being fixed by formatter and pipeline is passing

2021-05-10 09:05 UTC, HristiyanG commented
Is this still outstanding? Shall we merge / close this one? @thecryptofruit, @hswopeams

2021-05-10 12:32 UTC, hswopeams approved these changes

2021-05-10 12:32 UTC, merged