Reduce calls from BosonRouter to Cashier contract
bosonprotocol/contracts pull request #95
Opened 2021-04-21 08:28 UTC by ali2251

2021-04-21 15:18 UTC, hswopeams requested changes
updateEscrowTokensAmount is still being called on BosonRouter line 533

2021-04-21 15:54 UTC, HristiyanG approved these changes

2021-04-22 09:01 UTC, hswopeams approved these changes

2021-04-22 11:57 UTC, hswopeams approved these changes
Approve after rebase

2021-04-22 11:58 UTC, merged